services:
  directus:
    build:
      dockerfile: test.Dockerfile
    ports:
      - 8055:8055
    env_file: ".env.test"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://127.0.0.1:8055/server/health | grep -q '{\"status\":\"ok\"}'"]
      interval: 1m
      timeout: 10s
      start_period: 30s
      retries: 5
