name: setup-node-pnpm

description: Setup node and pnpm
inputs:
  npm-token:
    description: "Token to access the npm registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Update dependencies
      shell: bash
      run: sudo apt-get update

    - name: Install dependencies
      shell: bash
      run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - name: Install pnpm package manager
      uses: pnpm/action-setup@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
        scope: "@bicou"
        registry-url: "https://registry.npmjs.org/"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
